#!/bin/bash -e
APP=gusteau
WORKSPACE=${WORKSPACE:-.}

if [ -e "$HOME/.rvm/scripts/rvm" ]; then
  source  "$HOME/.rvm/scripts/rvm"
  rvm 1.9.3@${APP} --create
elif [ -e /usr/local/rvm/scripts/rvm ]; then
  source /usr/local/rvm/scripts/rvm
  rvm 1.9.3@${APP} --create
else
  echo "Going ahead with system Ruby `ruby -v`"
fi

